"""Generate the examples index fragment consumed by the Sphinx docs."""

from __future__ import annotations

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_ROOT = REPO_ROOT / "examples"
OUTPUT_PATH = REPO_ROOT / "docs" / "examples" / "generated_examples.rst"


def _example_paths() -> list[Path]:
    """Return all tracked Python examples in a stable order."""
    return sorted(
        path.relative_to(REPO_ROOT)
        for path in EXAMPLES_ROOT.rglob("*.py")
        if path.is_file()
    )


def _render() -> str:
    """Render the generated RST fragment."""
    lines = [
        "Generated Examples",
        "==================",
        "",
        ".. This file is generated by scripts/generate_example_docs.py.",
        "",
        "The current deterministic example scripts are:",
        "",
    ]
    for relative_path in _example_paths():
        lines.append(f"- ``{relative_path.as_posix()}``")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    """Write or validate the generated examples fragment."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = _render()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            raise SystemExit(
                "Generated examples docs are out of date. "
                "Run scripts/generate_example_docs.py."
            )
        print(f"{OUTPUT_PATH} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
